### ISSUE TITLE
PWAがシェアメニューに対応したけどURLが投稿欄に表示されない

### ISSUE THREAD

**Issue by kypkyp** [nuita/nuita#127]
#126 でシェア選択画面からNuitaの`/nweets/new`が開くようになったけど、フォーム内にURLが表示されない。

https://github.com/nuita/nuita/blob/1c8a8c3c3d16e7fd02dbccb1ea4614c860c2b0d5/app/assets/javascripts/manifest.json.erb#L23-L25

ここがちゃんと動いていない？

- https://nuita.net/nweets/new?text=hogehoge とか直接渡したらフォームに反映される
- https://web-share.glitch.me/ とかで試した、別のアプリは(textと)URL受け取れてる

**Comment by pastak** [comment]
思い出したけど、Chromeは理由は知らないけど、urlは常に空でtextとしてウェブページのURLを渡してくるのだった
