### ISSUE TITLE
スクロールし続けるとランダムえっちが消えてレイアウトが崩れる

### ISSUE THREAD

**Issue by machida4** [nuita/nuita#153]
## 概要

windows10
chrome 81.0.4044.129（Official Build）

chromeの拡張なしでも確認

## スクショ

https://gyazo.com/61b39976604155ff42c9f787b75a1e7d

**Comment by kypkyp** [comment]
！！！！！！！！！！！！！１

試してみた感じ特定のヌイートが映ると崩れるみたいなので、おそらくタイトルが長すぎるカードとか出てくるとカラム落ちするのかな
タイトルの長さ制限を厳しくする方向で解決を試みます

**Comment by kypkyp** [comment]
DLSiteResolverの不具合で取得できなかったカードが悪さしてたみたいです(#152 で修正済み)
以前 #130 でオカズの画像が非表示になってたときもカラム落ちしてたので、
画像あるはずのオカズで実はなかったりするとレイアウト壊れるのかも

とりあえず解決したので閉じておきます

**Comment by kypkyp** [comment]
正常に取得できなかったリンクを表示するべきかどうか（表示するとレイアウト崩れる？）について #155 を立てました
