### ISSUE TITLE
FF以外にもフォロー、フォロワー、いいねを公開すべきか？

### ISSUE THREAD

**Issue by kypkyp** [nuita/nuita#166]
現在、Nuitaのユーザーページ(例: https://nuita.net/users/sAJzW2uUk55x2D5u) では相互FFのユーザー以外は「いいね」「フォロー」「フォロワー」の一覧を見ることができません。
<img width="284" alt="スクリーンショット 2020-05-25 22 38 35" src="https://user-images.githubusercontent.com/19870474/82817767-85045680-9ed8-11ea-88b0-8e172d666b14.png">
<img width="284" alt="スクリーンショット 2020-05-25 22 40 46" src="https://user-images.githubusercontent.com/19870474/82817921-ce54a600-9ed8-11ea-80ba-34aa4363a52c.png">

この機能を実装していたときには間違いなく人間不信気味だったのですが、ともかく、人のいいねとかフォロワー見れてもいいかな？という気がしてきたので、この仕様を変えて誰でもいいねやフォロワー見れるようにしたほうがいいか迷っています。

**Comment by ahis1503** [comment]
射精報告の時点でこれ以上ないほどにさらけ出している気がするので、内容だけ見られたくない人はあまり想像が付かないですね

強いていうのであれば自分からはオカズを共有せずに他人のヌイートを見ていただけのユーザーは趣味嗜好がバレるというのがありそうですかね。実際問題として存在するのかは怪しいですが
