### ISSUE TITLE
nweets#newにおいて無限スクロールが壊れている

### ISSUE THREAD

**Issue by hidesys** [nuita/nuita#172]
スクロールしていくと、当該ページそれ自身をヌイートとして誤ってロードしていて、ページの中にページを入れ子で読み込んでいます
![image](https://user-images.githubusercontent.com/1846285/83529222-01c0b180-a525-11ea-9eb5-772772f47933.png)

**Comment by hidesys** [comment]
https://github.com/nuita/nuita/blob/6f15b3bd719828db1423de5494048eb458ff25f8/app/frontend/src/infinite_scroll.ts#L32

ここは `let morePostsUrl = new URL(location.origin);` であるべきだと思います。

（できればJSONのみを返すAPIは名前空間ごと変えたほうがいいと思いますが、さしあたりバグ修正としてです）

**Comment by ahis1503** [comment]
#167 でトップページのpagesコントローラーだけ書き換えて新規登録ページのnweetsコントローラーを変えるのを忘れてたのが原因っぽいですね

https://github.com/nuita/nuita/blob/master/app/controllers/nweets_controller.rb#L5-L13

トップページにbefore付きで取得するのでも良さそうですが、nweetsコントローラー側に古い処理が残ってしまうので、こっちを更新したほうが良さそうです
