### ISSUE TITLE
Nuita側で画像をキャッシュさせる

### ISSUE THREAD

**Issue by ahis1503** [nuita/nuita#175]
今は各サービスから直接画像を読み込んでいるけど、外部からサービス側に負荷を掛けるような感じになってしまうから、あまり良くなさそう

ユーザーがそこまで多くないうちは問題ないだろうけど、QiitaとかSlack、GitHubも、リンクされた画像を内部でキャッシュしているみたい

どうキャッシュするのが良いのかはよく分からないけど、URLをキーにして画像をアバターと同じように保存するとか、アクセスされたら単に一定期間メモリ上に載せておくとかでも実装はできそう

**Comment by kypkyp** [comment]
今はHTTPの画像を取得するときにだけCamoを通す設定にしてありますが(#144, #146)、
外部の画像すべてCamo経由にしてもいいかもしれませんね。
ところでCamoってキャッシュとかもいい感じにしてくれてるのかな……？少し調べてみます

**Comment by kypkyp** [comment]
とりあえずhttpsの画像もcamo通す方向性で行きます

**Comment by ahis1503** [comment]
#230 でcamo外したのでreopenですね

camoを代替できそうなproxyを見つけました（キャッシュのほかにリサイズもできるみたい）
https://github.com/willnorris/imageproxy
camoで失敗していたのが単に高頻度でのアクセスでブロックされたのが原因だとするならキャッシュで改善できるかもです

**Comment by kypkyp** [comment]
よさそう！今週あたり試してみます

> reopen
たしかに

**Comment by kypkyp** [comment]
#255 #257
