### ISSUE TITLE
/users/edit のパスワード再設定画面をいい感じにする

### ISSUE THREAD

**Issue by kypkyp** [nuita/nuita#188]
<img width="756" alt="スクリーンショット 2020-06-13 11 28 12" src="https://user-images.githubusercontent.com/19870474/84558058-e185c380-ad6a-11ea-8d83-9c21a3255041.png">

現行のパスワード再設定のフォームはプロフィール変更の領域にあって見苦しいし、確認用のパスワードと紛らわしいので、他のフォームとは独立した場所に置きたい

下図のようにモーダルとして表示できたらナウくていいと思う（見た目とか内容は全く下図に従わなくていいです）

![modal](https://user-images.githubusercontent.com/19870474/84558053-d29f1100-ad6a-11ea-8164-515f2d994f9b.png)

上図だとモーダルの項目2つだけど、これまでのパスワード入力する欄も作ったら現行のDeviseの設定と同じまますんなりいけるかも

**Comment by ahis1503** [comment]
モーダルにしてしまうとバリデーションに引っかかったときの遷移で閉じてしまってちょっと分かりづらいように感じたので、こんなセクションを区切ってみたんですけど、１つのフォームとして扱われてしまうのかエラーメッセージが両方に表示されてしまうみたい...

![image](https://user-images.githubusercontent.com/65934004/84560310-a8a31a00-ad7d-11ea-98c1-7cd896f97b1f.png)

**Comment by kypkyp** [comment]
もしPR出してくれたら見ます！

**Comment by kypkyp** [comment]
画面ごとリニューアルしたのでクローズ
