### ISSUE TITLE
ユーザー詳細画面(/users/***)のページのレイアウトが壊れてる

### ISSUE THREAD

**Issue by kypkyp** [nuita/nuita#193]
<img width="419" alt="スクリーンショット 2020-06-14 23 16 27" src="https://user-images.githubusercontent.com/19870474/84595855-39b8e480-ae95-11ea-9524-93af816b4fcd.png">

- 画面の横幅が一定以下になると崩壊するみたい
- グローバルタイムラインだと何も起こらない
- ユーザーの日ごとのヌイート一覧(`/users/***?date=***`)が表示されない

<img width="476" alt="スクリーンショット 2020-06-14 23 20 00" src="https://user-images.githubusercontent.com/19870474/84595924-a6cc7a00-ae95-11ea-8ff7-4dc2b4655689.png">

- なぜ……

**Comment by ahis1503** [comment]
最近の変更を片っ端から試してみたら #190 以降で`bundle install`を実行した場合だけ再現することが分かった.....
