### ISSUE TITLE
Github風のUIのコントラスト強くする？

### ISSUE THREAD

**Issue by kypkyp** [nuita/nuita#194]
<img src="https://gyazo.com/f44cb2b128dd463cfbbe1d4dc8260620.png">

確かに見づらい気もする（ヌイートしはじめちゃえば意味わかるだろうけど……）

**Comment by ahis1503** [comment]
最初のヌイートするまで分かりづらいということなら、１つもないときはグラフの代わりに「記録なし」とか表示してもいいのかも？GitHubのような日別のヒートマップはあまり馴染みがない人も多いだろうし

**Comment by kypkyp** [comment]
よさそう！確かにそっちの方がグラフの説明にもなりそうだしいいですね！

**Comment by kypkyp** [comment]
Githubっぽくはなくなったけど、いい感じにリニューアルできた気がする。mouseoverするとtooltipで日付と件数が表示される

<img width="315" alt="スクリーンショット 2021-05-03 17 15 21" src="https://user-images.githubusercontent.com/19870474/116854736-26d90b00-ac33-11eb-9a6b-7632eb7dac4e.png">
