### ISSUE TITLE
DockerfileをNuitaのレポジトリに同梱する

### ISSUE THREAD

**Issue by kypkyp** [nuita/nuita#241]
[ahis1503/nuita-docker](https://github.com/ahis1503/nuita-docker)

だいたいのプロジェクトはプロダクト自体のレポジトリにDockerfile同梱してる気がするので、Nuitaも一緒に管理する？
そのうち本番環境もDockerに移行したい。

**Comment by kypkyp** [comment]
@ahis1503 
Nuitaのレポジトリに[ahis1503/nuita-docker](https://github.com/ahis1503/nuita-docker)の内容を同梱することを思いついたのですが、いかがでしょうか？  
Nuitaのほうで環境を変えたときの管理が楽になるかなと個人的に思っています。
僕のDocker自体に対する知識や経験がほぼゼロなので、何か意見やアドバイスいただけるととても嬉しいです！

**Comment by ahis1503** [comment]
nuita-dockerはnuita自体に変更を加えずにdocker環境に入れるために、本来のdockerからはかなりかけ離れた使い方をしてるので、nuta自体に同梱するのであれば、新たに組んだほうが良いと思うので後でPR出します
