### ISSUE TITLE
遡ってヌイートしたい

### ISSUE THREAD

**Issue by Tetsuyamin** [nuita/nuita#29]
射精した直後って頭が働かなくなって、すぐにヌイートとかできないので、かなり事後報告になってしまいがちなんですよね。

**Comment by kypkyp** [comment]
わかる

**Comment by Tetsuyamin** [comment]
まぁ無法地帯になってもあれなので、1日以内とかだと十分ですかね～（僕は丸1日忘れてたので十分じゃないですが…）
