### ISSUE TITLE
Docker 環境構築の手順書通りにやってもうまく構築できない

### ISSUE THREAD

**Issue by shunyama** [nuita/nuita#382]
https://github.com/nuita/nuita#docker

> コンテナ上で依存関係をインストールします。
> $ docker-compose run --rm app bundle install && yarn install --check-files

上記コマンドを叩いても、

> コマンド 'yarn' が見つかりません。次の方法でインストールできます:
sudo apt install cmdtest

と出る。（当方のローカルに yarn がインストールされてないから）

Docker コンテナ内で走らせる必要があるから、

`docker-compose run --rm app bundle install`

`docker-compose run --rm app yarn install --check-files`

と2つに分けるか、

`docker-compose run --rm app sh -c 'bundle install && yarn install --check-files'`

とすればOK。

**Comment by kypkyp** [comment]
確かに！！！！！！！！issue & PRありがとうございます 🙇 🙇 🙇 🙇 🙇 🙇 🙇
